apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: postgres
spec: {}
status: {}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: postgres
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_DB: cHNfZGI=            # base64 encoded 'ps_db'
  POSTGRES_USER: cHNfdXNlcg==       # base64 encoded 'ps_user'
  POSTGRES_PASSWORD: U2VjdXJlUGFzc3dvcmQ=  # base64 encoded 'SecurePassword'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: postgres
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: postgres
  labels:
    app: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
      - name: init-postgres
        image: busybox
        command: ["sh", "-c", "rm -rf /var/lib/postgresql/data/*"]
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-vol
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
              name: postgres-secret
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-vol
      volumes:
        - name: postgres-vol
          persistentVolumeClaim:
            claimName: postgres-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: postgres
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres